lista=[{'pregunta': '¿Cuándo finalizó la II Guerra Mundial?', 'a': '1945', 'b': '1954', 'c':'1937' ,'correcta': 'a', 'tema':'Historia'}, 
       {'pregunta': '¿Cuánto dura un round de boxeo masculino?', 'a': '5 min.', 'b': '3 min.', 'c':'2 min.' ,'correcta': 'b','tema':'Deportes'},
       {'pregunta': '¿A qué saga pertenece el personaje de Katniss Everdeen?', 'a': 'Harry Potter', 'b': 'Juegos del Hambre', 'c':'Señor de los Anillos' ,'correcta': 'b','tema':'Cine'},
       {'pregunta': '¿En qué año llegó Cristóbal Colón a América?', 'a': '1942','b': '1492', 'c':'1945' ,'correcta': 'b', 'tema':'Historia'}, 
       {'pregunta': '¿Cuántos huesos hay en el cuerpo humano?', 'a': '126', 'b': '206', 'c':'166' ,'correcta': 'b','tema':'Naturaleza y Ciencia'},
       {'pregunta': '¿Cómo se llama el estadio del F.C. Barcelona?', 'a': 'Santiago Bernabéu', 'b': 'Metropolitano', 'c':'Camp Nou' ,'correcta': 'c','tema':'Deportes'},
       {'pregunta': '¿Qué planeta es el que se encuentra más cerca del Sol?', 'a': 'Mercurio', 'b': 'Marte', 'c':'Jupiter' ,'correcta': 'a','tema':'Naturaleza y Ciencia'},
       {'pregunta': '¿Cuánto dura un partido de rugby?', 'a': '80 min.', 'b': '60 min.', 'c':'45 min.' ,'correcta': 'a','tema':'Deportes'},
       {'pregunta': '¿Qué es más grande un átomo o una célula?', 'a': 'átomo', 'b': 'son iguales', 'c':'célula' ,'correcta': 'c','tema':'Naturaleza y Ciencia'},
       {'pregunta': '¿Quién protagonizó la película Gladiator?', 'a': 'Kurt Russell', 'b': 'Russell Brand', 'c':'Russell Crowe' ,'correcta': 'c','tema':'Cine'},
       {'pregunta': '¿A qué editorial de comics pertenece Capitán América?', 'a': 'Marvel', 'b': 'DC', 'c':'Ninguna' ,'correcta': 'a','tema':'Cine'},
       {'pregunta': '¿Quién fue el último faraón de Egipto?', 'a': 'Akenatón', 'b': 'Tutankamón', 'c':'Ramsés III' ,'correcta': 'c','tema':'Historia'},
       {'pregunta': '¿Cuántos lados tiene un heptadecágono?', 'a': 'Dieciseis', 'b': 'Diecisete', 'c':'Quince' ,'correcta': 'b','tema':'Naturaleza y Ciencia'},
       {'pregunta': '¿Hace cuánto se extinguieron los dinosaurios?', 'a': '66.000.000 años', 'b': '13.000.000 años', 'c':'33.000.000 años' ,'correcta': 'a', 'tema':'Historia'},
       {'pregunta': '¿Qué selección ha ganado más Copas Mundiales de Fútbol?', 'a': 'Brasil', 'b': 'Francia', 'c':'Italia' ,'correcta': 'a','tema':'Deportes'},
       {'pregunta': '¿Cómo se llama la esposa de Shrek?', 'a': 'Aurora', 'b': 'Fiona', 'c':'Ariel' ,'correcta': 'b','tema':'Cine'}
      ]
